<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<databrowser>
    <title></title>
    <save_changes>true</save_changes>
    <show_legend>false</show_legend>
    <show_toolbar>true</show_toolbar>
    <grid>false</grid>
    <scroll>true</scroll>
    <update_period>3.0</update_period>
    <scroll_step>5</scroll_step>
    <start>-4 hours 0.0 seconds</start>
    <end>now</end>
    <archive_rescale>NONE</archive_rescale>
    <background>
        <red>255</red>
        <green>255</green>
        <blue>255</blue>
    </background>
    <title_font>Ubuntu|16|1</title_font>
    <label_font>Ubuntu|11|1</label_font>
    <scale_font>Ubuntu|10|0</scale_font>
    <legend_font>Ubuntu|10|0</legend_font>
    <axes>
        <axis>
            <visible>true</visible>
            <name>uSv</name>
            <use_axis_name>true</use_axis_name>
            <use_trace_names>false</use_trace_names>
            <right>false</right>
            <color>
                <red>0</red>
                <green>0</green>
                <blue>0</blue>
            </color>
            <label_font>|10|0</label_font>
            <scale_font>|10|0</scale_font>
            <min>-0.1</min>
            <max>2.1</max>
            <grid>false</grid>
            <autoscale>true</autoscale>
            <log_scale>false</log_scale>
        </axis>
    </axes>
    <annotations>
    </annotations>
    <pvlist>
        <pv>
            <display_name>RAD:ELSE:DoseIntegral</display_name>
            <visible>true</visible>
            <name>RAD:ELSE:DoseIntegral</name>
            <axis>0</axis>
            <color>
                <red>0</red>
                <green>255</green>
                <blue>0</blue>
            </color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>RAW</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:THERMO:DoseIntegral</display_name>
            <visible>true</visible>
            <name>RAD:THERMO:DoseIntegral</name>
            <axis>0</axis>
            <color>
                <red>0</red>
                <green>0</green>
                <blue>255</blue>
            </color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>RAW</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:Berthold:Int</display_name>
            <visible>true</visible>
            <name>RAD:Berthold:Int</name>
            <axis>0</axis>
            <color>
                <red>255</red>
                <green>0</green>
                <blue>255</blue>
            </color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>RAW</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:THERMO:IntegralGamma</display_name>
            <visible>true</visible>
            <name>RAD:THERMO:IntegralGamma</name>
            <axis>0</axis>
            <color>
                <red>0</red>
                <green>0</green>
                <blue>0</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:THERMO:IntegralNeutron</display_name>
            <visible>true</visible>
            <name>RAD:THERMO:IntegralNeutron</name>
            <axis>0</axis>
            <color>
                <red>159</red>
                <green>150</green>
                <blue>150</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:ELSE:IntegralGamma</display_name>
            <visible>true</visible>
            <name>RAD:ELSE:IntegralGamma</name>
            <axis>0</axis>
            <color>
                <red>255</red>
                <green>128</green>
                <blue>0</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:ELSE:IntegralNeutron</display_name>
            <visible>true</visible>
            <name>RAD:ELSE:IntegralNeutron</name>
            <axis>0</axis>
            <color>
                <red>150</red>
                <green>0</green>
                <blue>0</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:Berthold:IntGamma</display_name>
            <visible>true</visible>
            <name>RAD:Berthold:IntGamma</name>
            <axis>0</axis>
            <color>
                <red>30</red>
                <green>255</green>
                <blue>253</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <pv>
            <display_name>RAD:Berthold:IntNeutron</display_name>
            <visible>true</visible>
            <name>RAD:Berthold:IntNeutron</name>
            <axis>0</axis>
            <color>
                <red>255</red>
                <green>255</green>
                <blue>0</blue>
            </color>
            <trace_type>AREA</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <period>0.0</period>
            <ring_size>5000</ring_size>
            <request>OPTIMIZED</request>
            <archive>
                <name>All</name>
                <url>pbraw://10.0.4.57:11998/retrieval</url>
                <key>1</key>
            </archive>
        </pv>
        <formula>
            <display_name>limite</display_name>
            <visible>true</visible>
            <name>B</name>
            <axis>0</axis>
            <color>
                <red>255</red>
                <green>0</green>
                <blue>0</blue>
            </color>
            <trace_type>SINGLE_LINE</trace_type>
            <linewidth>2</linewidth>
            <point_type>NONE</point_type>
            <point_size>2</point_size>
            <waveform_index>0</waveform_index>
            <formula>x2-x2+2</formula>
            <input>
                <pv>RAD:THERMO:DoseIntegral</pv>
                <name>x2</name>
            </input>
        </formula>
    </pvlist>
</databrowser>